version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/TrafficReplayer"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
